apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-1-app
  template:
    metadata:
      labels:
        app: demo-1-app
    spec:
      containers:
        - name: demo-1-app
          image: vicentegarcia/demo-1-app:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---

apiVersion: v1
kind: Service
metadata:
  name: demo-1-app
spec:
  selector:
    app: demo-1-app
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-1-app
  labels:
    account: demo-1-app